#ifndef BONEFISH_LOGGING_LOGGING_HPP
#define BONEFISH_LOGGING_LOGGING_HPP

#ifdef BONEFISH_DEBUG
#define BONEFISH_TRACE(x) x
#else
#define BONEFISH_TRACE(x)
#endif

#endif // BONEFISH_LOGGING_LOGGING_HPP
